blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.arion2000.xyz/api/discord
    about: You can ask questions and exchange ideas with others on our Discord server.
